i = [28, 59, 72, 80, 142, 159];
filePath = '/home/mina/workspace/src/Git/dynamicSLAM/Data/GraphFiles/Trial_';

for j = 1: length(i)

disp(strcat('Trial ',num2str(i(j))))

results1 = load(strcat(filePath,num2str(i(j)),'/results1.mat'));
results1 = results1.results;
resultsP1 = load(strcat(filePath,num2str(i(j)),'/resultsP1.mat'));
resultsP1 = resultsP1.resultsP;
resultsSP1 = load(strcat(filePath,num2str(i(j)),'/resultsSP1.mat'));
resultsSP1 = resultsSP1.resultsSP;
resultsPA1 = load(strcat(filePath,num2str(i(j)),'/resultsPA1.mat'));
resultsPA1 = resultsPA1.resultsPA;
resultsSPA1 = load(strcat(filePath,num2str(i(j)),'/resultsSPA1.mat'));
resultsSPA1 = resultsSPA1.resultsSPA;
resultsPA2 = load(strcat(filePath,num2str(i(j)),'/resultsPA2.mat'));
resultsPA2 = resultsPA2.resultsPA;
resultsSPA2 = load(strcat(filePath,num2str(i(j)),'/resultsSPA2.mat'));
resultsSPA2 = resultsSPA2.resultsSPA;
resultsPA3 = load(strcat(filePath,num2str(i(j)),'/resultsPA3.mat'));
resultsPA3 = resultsPA3.resultsPA;
resultsSPA3 = load(strcat(filePath,num2str(i(j)),'/resultsSPA3.mat'));
resultsSPA3 = resultsSPA3.resultsSPA;

fprintf('ATE Translational & %0.3f %s %0.3f %s %0.3f %s %0.3f %s %0.3f %s %0.3f %s %0.3f %s %0.3f %s %0.3f %s',...
  results1.ATE_translation_error,...
  ' & ',resultsP1.ATE_translation_error,...
  ' & ',resultsSP1.ATE_translation_error,...
  ' & ',resultsPA1.ATE_translation_error,...
  ' & ',resultsSPA1.ATE_translation_error,...
  ' & ',resultsPA2.ATE_translation_error,...
  ' & ',resultsSPA2.ATE_translation_error,...
  ' & ',resultsPA3.ATE_translation_error,...
  ' & ',resultsSPA3.ATE_translation_error,' \\ \hline');
fprintf('\n')

fprintf('ATE Rotational & %0.3f %s %0.3f %s %0.3f %s %0.3f %s %0.3f %s %0.3f %s %0.3f %s %0.3f %s %0.3f %s',...
        results1.ATE_rotation_error,...
  ' & ',resultsP1.ATE_rotation_error,...
  ' & ',resultsSP1.ATE_rotation_error,...
  ' & ',resultsPA1.ATE_rotation_error,...
  ' & ',resultsSPA1.ATE_rotation_error,...
  ' & ',resultsPA2.ATE_rotation_error,...
  ' & ',resultsSPA2.ATE_rotation_error,...
  ' & ',resultsPA3.ATE_rotation_error,...
  ' & ',resultsSPA3.ATE_rotation_error,' \\ \hline');
fprintf('\n')

fprintf('RPE Translational & %0.3f %s %0.3f %s %0.3f %s %0.3f %s %0.3f %s %0.3f %s %0.3f %s %0.3f %s %0.3f %s',...
        results1.RPE_translation_error,...
  ' & ',resultsP1.RPE_translation_error,...
  ' & ',resultsSP1.RPE_translation_error,...
  ' & ',resultsPA1.RPE_translation_error,...
  ' & ',resultsSPA1.RPE_translation_error,...
  ' & ',resultsPA2.RPE_translation_error,...
  ' & ',resultsSPA2.RPE_translation_error,...
  ' & ',resultsPA3.RPE_translation_error,...
  ' & ',resultsSPA3.RPE_translation_error,' \\ \hline');
fprintf('\n')

fprintf('RPE Rotational & %0.3f %s %0.3f %s %0.3f %s %0.3f %s %0.3f %s %0.3f %s %0.3f %s %0.3f %s %0.3f %s',...
        results1.RPE_rotation_error,...
  ' & ',resultsP1.RPE_rotation_error,...
  ' & ',resultsSP1.RPE_rotation_error,...
  ' & ',resultsPA1.RPE_rotation_error,...
  ' & ',resultsSPA1.RPE_rotation_error,...
  ' & ',resultsPA2.RPE_rotation_error,...
  ' & ',resultsSPA2.RPE_rotation_error,...
  ' & ',resultsPA3.RPE_rotation_error,...
  ' & ',resultsSPA3.RPE_rotation_error,' \\ \hline');
fprintf('\n')

fprintf('ASE Translational & %0.3f %s %0.3f %s %0.3f %s %0.3f %s %0.3f %s %0.3f %s %0.3f %s %0.3f %s %0.3f %s',...
        results1.ASE_translation_error,...
  ' & ',resultsP1.ASE_translation_error,...
  ' & ',resultsSP1.ASE_translation_error,...
  ' & ',resultsPA1.ASE_translation_error,...
  ' & ',resultsSPA1.ASE_translation_error,...
  ' & ',resultsPA2.ASE_translation_error,...
  ' & ',resultsSPA2.ASE_translation_error,...
  ' & ',resultsPA3.ASE_translation_error,...
  ' & ',resultsSPA3.ASE_translation_error,' \\ \hline');
fprintf('\n')

fprintf('RPTE Translational & %0.3f %s %0.3f %s %0.3f %s %0.3f %s %0.3f %s %0.3f %s %0.3f %s %0.3f %s %0.3f %s',...
    results1.RPTE_translation_error,...
  ' & ',resultsP1.RPTE_translation_error,...
  ' & ',resultsSP1.RPTE_translation_error,...
  ' & ',resultsPA1.RPTE_translation_error,...
  ' & ',resultsSPA1.RPTE_translation_error,...
  ' & ',resultsPA2.RPTE_translation_error,...
  ' & ',resultsSPA2.RPTE_translation_error,...
  ' & ',resultsPA3.RPTE_translation_error,...
  ' & ',resultsSPA3.RPTE_translation_error,' \\ \hline');
fprintf('\n')

end